version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
            
  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox:/etc/blackbox_exporter
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml  # Add this line to mount Blackbox Exporter config
    command:
      - "--config.file=/etc/blackbox_exporter/blackbox.yml"
      
  windows_exporter:
    image: prom/windows-exporter
    container_name: windows_exporter
    ports:
      - "9182:9182"
    volumes:
      - ./windows_exporter:/etc/windows_exporter
    command:
      - "--config.file=/etc/windows_exporter/windows_exporter.yml"