{
 "title": "Docker Container Dashboard",
 "description": "Dashboard that has visualizations for monitoring metrics from Docker containers",
 "tags": [
  "cAdvisor",
  "Docker-Metrics",
  "Containers",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Details",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>Container Monitoring</h1>\r\nSystem and container monitoring\r\n<p>- Aftab S</p>"
   }
  },
  {
   "title": "Containers Overview",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state)(engine_daemon_container_states_containers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "description": "The number of CPUs that the host system of the engine has.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_processes{job=\"windows-exporter\",instance=\"host.docker.internal:9182\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{job=\"windows-exporter\",instance=\"host.docker.internal:9182\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Memory Usage",
   "type": "bargauge",
   "description": "Memory Usage per Prometheus Jobs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=\"windows-exporter\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * windows_os_physical_memory_free_bytes{job=~\"windows-exporter\"} / windows_cs_physical_memory_bytes{job=~\"windows-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Check Duration",
   "type": "timeseries",
   "description": "The number of seconds it takes to prepare to run health checks",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "engine_daemon_health_check_start_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest CPU-Intensive Containers",
   "type": "piechart",
   "description": "Top 5 most CPU-intensive containers",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (name) (rate(container_cpu_usage_seconds_total[5m]))) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage Memory per Container",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name) /1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "description": "The total received bytes rate per second for each container",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "description": "The total transmit bytes rate per second for each container",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Stats - WiFi Adapter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_sent_total{job=\"windows-exporter\",instance=\"host.docker.internal:9182\",nic!~'isatap.*|VPN.*'}[5m])*8>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (instance) (irate(windows_logical_disk_read_bytes_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (instance) (irate(windows_logical_disk_write_bytes_total[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(irate(windows_net_bytes_total{job=\"windows-exporter\",instance=\"host.docker.internal:9182\",nic!~'isatap.*|VPN.*'}[5m]) * 8 / windows_net_current_bandwidth_bytes{job=\"windows-exporter\",instance=\"host.docker.internal:9182\",nic!~'isatap.*|VPN.*'}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}