{
 "title": "Docker Container Dashboard",
 "description": "Dashboard that has visualizations for monitoring metrics from Docker containers",
 "tags": [
  "cAdvisor",
  "Docker-Metrics",
  "Containers",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Containers Overview",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state)(engine_daemon_container_states_containers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "description": "The number of CPUs that the host system of the engine has.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "engine_daemon_engine_cpus_cpus", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Health Check Duration",
   "type": "timeseries",
   "description": "The number of seconds it takes to prepare to run health checks",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "engine_daemon_health_check_start_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest CPU-Intensive Containers",
   "type": "piechart",
   "description": "Top 5 most CPU-intensive containers",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (name) (rate(container_cpu_usage_seconds_total[5m]))) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Memory Usage",
   "type": "bargauge",
   "description": "Memory Usage per Prometheus Jobs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "description": "The total received bytes rate per second for each container",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "description": "The total transmit bytes rate per second for each container",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage Memory per Container",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name=~\".+\"}) by (name) /1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}