{
 "title": "Abilytics Dashboard",
 "description": "Dashboard for monitoring Abilytics Website",
 "tags": [
  "prometheus",
  "blackbox"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Abilytics Website Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"https://abilytics.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://abilytics.com\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://abilytics.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://portfolio.aftabs.co\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Probe Failure Due to Regex",
   "type": "gauge",
   "description": "It is a counter that tracks the number of times a probe to the URL https://portfolio.aftabs.co has failed due to a regular expression match. The instance parameter is a label that is used to identify the URL of the probe. The probe_failed_due_to_regex metric is typically used to monitor the health of a web application by checking for errors that are returned by the application. If the probe fails due to a regular expression match, it means that the application returned an error message that matches the specified regular expression. ",
   "gridPos": { "h": 6, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_failed_due_to_regex{instance=\"https://abilytics.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=\"https://portfolio.aftabs.co\"} - time()",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=\"https://abilytics.com\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Protocol",
   "type": "stat",
   "description": "This command is typically used to monitor the health of a network by checking the IP protocol of a given target. If the probe is successful, it will return a value of 4 or 6, indicating that the target is using IPv4 or IPv6, respectively. If the probe is unsuccessful, it will return a value of 0, indicating that the target is not reachable or that the probe was unable to determine the IP protocol of the target.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ip_protocol{instance=\"https://portfolio.aftabs.co\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://portfolio.aftabs.co\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://abilytics.com\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Duration (All Phases)",
   "type": "timeseries",
   "description": "\nHTTP duration is a measure of how long it takes for an HTTP request to complete all of its phases. This includes the time it takes to DNS lookup, connect to the server, send the request, receive the response, and render the page. HTTP duration is an important metric for measuring the performance of a web application.\n\nThere are four phases of an HTTP request:\n\nDNS lookup: This is the time it takes to resolve the hostname of the server to an IP address.\nConnect: This is the time it takes to establish a connection to the server.\nRequest: This is the time it takes to send the HTTP request to the server.\nResponse: This is the time it takes to receive the HTTP response from the server.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"https://abilytics.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Duration (All Phases)",
   "type": "bargauge",
   "description": "\nHTTP duration is a measure of how long it takes for an HTTP request to complete all of its phases. This includes the time it takes to DNS lookup, connect to the server, send the request, receive the response, and render the page. HTTP duration is an important metric for measuring the performance of a web application.\n\nThere are four phases of an HTTP request:\n\nDNS lookup: This is the time it takes to resolve the hostname of the server to an IP address.\nConnect: This is the time it takes to establish a connection to the server.\nRequest: This is the time it takes to send the HTTP request to the server.\nResponse: This is the time it takes to receive the HTTP response from the server.",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"https://abilytics.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=\"https://abilytics.com\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Duration (All Phases)",
   "type": "timeseries",
   "description": "\nHTTP duration is a measure of how long it takes for an HTTP request to complete all of its phases. This includes the time it takes to DNS lookup, connect to the server, send the request, receive the response, and render the page. HTTP duration is an important metric for measuring the performance of a web application.\n\nThere are four phases of an HTTP request:\n\nDNS lookup: This is the time it takes to resolve the hostname of the server to an IP address.\nConnect: This is the time it takes to establish a connection to the server.\nRequest: This is the time it takes to send the HTTP request to the server.\nResponse: This is the time it takes to receive the HTTP response from the server.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"https://abilytics.com\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}